### ISSUE TITLE
NanoR reporting 0 for Fast5 files

### ISSUE THREAD

**Issue by kuskovich** [davidebolo1993/NanoR#18]
When I load my sequencing data from the MinION sequencer and try to run NanoPrepareM, I see this message:
Passed FAST5: 0
Failed FAST5: 0
Skipped FAST5: 0
Done

I am not sure whether it is not working because of the directory (I have attached a picture). Any suggestions would be greatly appreciated!

<img width="1279" alt="Screen Shot 2020-11-18 at 9 25 35 AM" src="https://user-images.githubusercontent.com/74675421/99565358-60b59e00-2980-11eb-9350-c111fc152672.png">

**Comment by davidebolo1993** [comment]
Hi @kuskovich, 

sorry, but it's hard to tell if this issue is somehow related to the content of your directory. Which directory are you actually giving as input to DataPass/DataFail (data_1st?). NanoPrepareM finds .fast5 files recursively, but maybe there is something wrong with the content of those "barcode*" folders. Can you also try to pass something like "/path/to/fast5_fail/barcode1" as DataFail and "/path/to/fast5_pass/barcode1" to DataPass?

Thanks,

Davide

**Comment by davidebolo1993** [comment]
Any updates on this?

**Comment by kuskovich** [comment]
Hello,

The issue seems to have resolved itself. I think it was an issue with my computer not having the capacity to run such a large data set. I'm working with a team on this project and they were able to successfully run the commands and generate the graphs. Thanks very much!

**Comment by davidebolo1993** [comment]
Glad it works!

Best,

Davide
