### ISSUE TITLE
add option to keep plot objects for ggplot tuneup

### ISSUE THREAD

**Issue by splaisan** [davidebolo1993/NanoR#4]
I love the package but find that some plots would benefit from some ggplot2 alterations like colours and colour-fills (I am colour blind and cannot read your current plots easily).

Would it be possible to allow keeping the plot objects in the Environment (or the dataframe behind each pot, or the general dataframe for all plots) so that we can use ggplot2 and alter their format or content.

Probably many other applications here like zooming in a plot, removing some variables ...

Thanks for the nice tools

**Comment by davidebolo1993** [comment]
Hi @splaisan, thank You for your comment.

The general dataframe for all plots is available inside the folder in which results for each run are stored. NanoStats use that table for all the plots and the script for that function is available inside the 'Script' folder, so that one can easily modify something if needed. Of course, as You mentioned, behind every plot, as they are ggplot2-based, there is another data.frame object but I thought the users wouldn't have too much interested on these, so I decided not to store them. Let me know if these few informations are useful and if you are able to use NanoStats function easily, otherwise I'll slightly modify the script to keep the data you need inside the environment (or to output them in the folder in which results are stored).


Thank You again for the positive feedback on the package !

**Comment by splaisan** [comment]
Thanks @davidebolo1993 ,
I found the table and should be able to recreate similar plots from the scripts indeed.
If in a later version you could add the option to keep the plot objects (default to No to not change the current behaviour), this might be useful when one wants to create a complex QC report and include some or all of your plots in specific grid/layouts or combinations together with some summary tables.
BTW: Would you happen to have a link to some test data from gridion specifically, the one I found here is from minion and I would like to prepare for our own to come GI data.
Best

**Comment by davidebolo1993** [comment]
Hi @splaisan 

in the README file of the repository I added a link that you can use to download both a larger MinION dataset and a GridION dataset (sequencing summary files and .fastq files). In addition, all the functions that can deal with .fastq extraction/.fastq filtering now support a minimum quality treshold defined by the user. This option was added because we saw that setting a treshold higher than the default one (7) can help reduing the error rate in alignment files generated during downstream analyses. (For more informations, just have a look at revised https://www.biorxiv.org/content/10.1101/514232v2, Supporting Informations S2).  In addition, NanoStatsM and NanoStatsG now are faster in computing statistics, as large datasets required a little bit too much for plotting.

Best

**Comment by splaisan** [comment]
Grazie Davide!
I will look into this asap now that we finally have the gridION in house.
Have a great time in the beautiful Toscana, I spent many holidays near Chiusdino (SI) when I was younger, great memories.
Stephane

**Comment by davidebolo1993** [comment]
Well, Thank You ! To be honest, I'm now working at EMBL Heidelberg as part of my PhD Fellowship but, of course, I'm in love with my beautiful Tuscany.

If You notice any issues, please let me know.

Best,


Davide
